name: Build and deploy Python app to Azure Web App - 9ai-2nd-team-app-service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # 백엔드 폴더 수정 시에만 작동
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
                
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/        # 핵심: backend 폴더 내부를 루트로 업로드
            !backend/antenv/ # 가상환경 폴더 제외

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66AF6112E77C47E89CE0C6B25C793F2E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1887BF60BD1C4A28AADD1863D1B35279 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C228FFB582194E21B0A3FFAEE07952C2 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: '9ai-2nd-team-app-service'
          slot-name: 'Production'
